version: '3'
services:
  postgres-db:
    image: "postgres:12"
    env_file:
      - .env
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Containerfile
      args:
        NODE_ENV: production
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:${API_PORT}/api/health/app || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
